language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - ./vendor/bin/phpunit
  
after_script:
  - ./vendor/bin/php-cs-fixer fix ./src/
  - ./vendor/bin/php-cs-fixer fix ./tests/
