language: php

php:
  - 5.4
  - 5.5
  - hhvm
  - 7

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit
  
after_script:
  - ./vendor/bin/php-cs-fixer fix ./src/
  - ./vendor/bin/php-cs-fixer fix ./tests/
  - git commit -a -m "automatic code style fix in travis"
  - git push
