language: php

php:
  - 5.4
  - 5.5
  - hhvm
  - 7

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit
  
after_script:
  - ./vendor/bin/php-cs-fixer fix ./src/
  - ./vendor/bin/php-cs-fixer fix ./tests/
  - git config --global user.name "Yordi Pauptit @ Travis CI"
  - git config --global user.email "yordipauptit@hotmail.com"
  - git config --global push.default matching
  - git commit -a -m "automatic code style fix in travis"
  - git push
