language: php

php:
  - 5.4
  - 5.5
  - hhvm
  - 7

before_script:
  - composer self-update
  - composer update

script:
  - ./vendor/bin/phpunit
  
after_script:
  - ./vendor/bin/php-cs-fixer fix ./src/
  - ./vendor/bin/php-cs-fixer fix ./tests/
